export enum CommonErrorCode {
  // Authentication errors
  UNAUTHORIZED_NO_TOKEN = 'UNAUTHORIZED_NO_TOKEN',
  UNAUTHORIZED_INVALID_TOKEN = 'UNAUTHORIZED_INVALID_TOKEN',

  // Value object errors
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',

  // General errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Storage errors
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  FILE_SIZE_EXCEEDS_LIMIT = 'FILE_SIZE_EXCEEDS_LIMIT',
}
