export enum StorageErrorCode {
  BUCKET_NOT_FOUND = 'BUCKET_NOT_FOUND',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_DELETION_FAILED = 'FILE_DELETION_FAILED',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
}
