export enum UserErrorCode {
  // User profile errors
  INVALID_USER = 'INVALID_USER',
  USER_PROFILE_NOT_FOUND = 'USER_PROFILE_NOT_FOUND',
  USER_PROFILE_ALREADY_EXISTS = 'USER_PROFILE_ALREADY_EXISTS',
}
