export enum GoalErrorCode {
  INVALID_GOAL = 'INVALID_GOAL',
  GOAL_NOT_FOUND = 'GOAL_NOT_FOUND',
  GOAL_INVALID_TARGET_AMOUNT = 'GOAL_INVALID_TARGET_AMOUNT',
  GOAL_INVALID_DUE_DATE = 'GOAL_INVALID_DUE_DATE',
  GOAL_TITLE_ALREADY_EXISTS = 'GOAL_TITLE_ALREADY_EXISTS',
  GOAL_INSUFFICIENT_BALANCE = 'GOAL_INSUFFICIENT_BALANCE',
}
