export enum OnboardingErrorCode {
  // Profile errors
  PROFILE_NOT_FOUND = 'ONBOARDING_PROFILE_NOT_FOUND',
  PROFILE_ALREADY_EXISTS = 'ONBOARDING_PROFILE_ALREADY_EXISTS',
  PROFILE_INVALID_AMOUNT = 'ONBOARDING_PROFILE_INVALID_AMOUNT',
  PROFILE_ALREADY_COMPLETED = 'ONBOARDING_PROFILE_ALREADY_COMPLETED',
  PROFILE_NOT_FOUND_INFORMATION = 'ONBOARDING_PROFILE_NOT_FOUND_INFORMATION',

  // Message errors
  MESSAGE_NOT_FOUND = 'ONBOARDING_MESSAGE_NOT_FOUND',
  MESSAGE_INVALID_CONTENT = 'ONBOARDING_MESSAGE_INVALID_CONTENT',
  MESSAGE_INVALID_SENDER = 'ONBOARDING_MESSAGE_INVALID_SENDER',
}
