name: CI

on:
  push:
    branches: [main, staging, develop]
  pull_request:
    branches: [main, staging, develop]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: false
        type: string
        default: 'staging'

jobs:
  e2e-testing:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || (github.ref == 'refs/heads/staging' && 'staging' || 'staging')) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          cat > .env << 'EOL'
          ${{ secrets.APP_ENV }}
          EOL

      - name: Generate Prisma client
        run: npm run prisma:generate

      - name: Run linting
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Run e2e tests
        run: npm run test:e2e
