name: Deploy to Digital Ocean

on:
  push:
    branches: [main, staging]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          cat > .env << 'EOL'
          ${{ secrets.APP_ENV }}
          EOL

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/infina-pfa-be:${{ github.ref == 'refs/heads/main' && 'latest' || 'staging' }}
          cache-from: type=registry,ref=registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/infina-pfa-be:buildcache
          cache-to: type=registry,ref=registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/infina-pfa-be:buildcache,mode=max

      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Login to DO Container Registry
            doctl registry login

            # Create deployment directory if it doesn't exist
            mkdir -p /opt/infina-pfa-be/${{ github.environment }}
            cd /opt/infina-pfa-be/${{ github.environment }}

            # Create or update docker-compose.yml
            cat > docker-compose.yml << 'EOL'
            version: '3.8'

            services:
              api:
                image: registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/infina-pfa-be:${{ github.ref == 'refs/heads/main' && 'latest' || 'staging' }}
                ports:
                  - '3000:3000'
                env_file:
                  - .env
                restart: unless-stopped

            volumes:
              postgres_data:
            EOL

            # Create .env file from secrets
            cat > .env << 'EOL'
            ${{ secrets.APP_ENV }}
            EOL

            # Pull the latest image
            docker-compose pull

            # Restart services
            docker-compose down
            docker-compose up -d

            # Clean up
            docker system prune -af
