name: Deploy to Digital Ocean

on:
  push:
    branches: [main, staging]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          cat > .env << 'EOL'
          ${{ secrets.APP_ENV }}
          EOL

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/infina-pfa-be:${{ github.ref == 'refs/heads/main' && 'latest' || 'staging' }}
          cache-from: type=registry,ref=registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/infina-pfa-be:buildcache
          cache-to: type=registry,ref=registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/infina-pfa-be:buildcache,mode=max

      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo apt update
              sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt update
              sudo apt install -y docker-ce
              sudo usermod -aG docker $USER
            fi

            # Install Docker Compose if not installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Install doctl if not installed
            if ! command -v doctl &> /dev/null; then
              echo "Installing doctl..."
              cd ~
              wget https://github.com/digitalocean/doctl/releases/download/v1.101.0/doctl-1.101.0-linux-amd64.tar.gz
              tar xf doctl-1.101.0-linux-amd64.tar.gz
              sudo mv doctl /usr/local/bin
              rm doctl-1.101.0-linux-amd64.tar.gz
              
              # Configure doctl with API token
              doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            fi

            # Login to DO Container Registry
            doctl registry login

            # Create deployment directory if it doesn't exist
            sudo mkdir -p /opt/infina-pfa-be/${{ github.environment }}
            sudo chown -R $(whoami):$(whoami) /opt/infina-pfa-be
            cd /opt/infina-pfa-be/${{ github.environment }}

            # Create or update docker-compose.yml
            cat > docker-compose.yml << 'EOL'
            version: '3.8'

            services:
              api:
                image: registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/infina-pfa-be:${{ github.ref == 'refs/heads/main' && 'latest' || 'staging' }}
                ports:
                  - '3000:3000'
                env_file:
                  - .env
                restart: unless-stopped

            volumes:
              postgres_data:
            EOL

            # Create .env file from secrets
            cat > .env << 'EOL'
            ${{ secrets.APP_ENV }}
            EOL

            # Pull the latest image
            sudo docker-compose pull

            # Restart services
            sudo docker-compose down
            sudo docker-compose up -d

            # Clean up
            sudo docker system prune -af
